### ISSUE TITLE
Closing Vifm also closes window

### ISSUE THREAD

**Issue by sQVe** [vifm/vifm.vim#25] opened 2019-05-28 21:00 UTC
The behaviour when closing `vifm` in `nvim` has changed since 491d4427eb258b0d0a6f79e7f7c626579997e38a. If you have two windows open and open `vifm` in one of them the window will close if you run `:q` in `vifm`.

Is this the indented behaviour because it feels off to me?

@rbong :point_up:

**Comment by sQVe** [comment] 2019-05-28 21:17
I see the same behavior when opening a file too.

![Peek 2019-05-28 23-15](https://user-images.githubusercontent.com/2284724/58512935-9bc97d80-819e-11e9-8b75-4abcaffe6443.gif)

**Comment by rbong** [comment] 2019-05-29 00:13
That's definitely unintended behaviour. There's also window closing issues with netrw replacement. Fix coming shortly.

**Closed** 2019-05-30 20:39 UTC
